{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{template "jupyterhub.fullname" .}}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{template "jupyterhub.fullname" .}}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{template "jupyterhub.fullname" .}}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{template "jupyterhub.fullname" .}}-hub
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{template "jupyterhub.fullname" .}}-hub
  apiGroup: rbac.authorization.k8s.io
{{- end }}
